/* Software systems mini project : Railway ticket booking system
 */


#define LOGIN 1
#define ADD_ACCOUNT 2
#define DELETE_ACCOUNT 3
#define SEARCH_ACCOUNT 4
#define MODIFY_ACCOUNT 5
#define ADD_TRAIN 6
#define DELETE_TRAIN 7
#define MODIFY_TRAIN_DETAILS 8
#define SEARCH_TRAIN 9
#define LOGOUT_ADMIN 101

#define BOOK_TICKET_USER 10
#define CANCEL_TICKET_USER 11
#define MODIFY_TICKET_USER 12
#define PREV_BOOKINGS_USER 13
#define UPDATE_BOOKING_USER 14
#define LOGOUT_USER 102

#define BOOK_TICKET_AGENT 15
#define CANCEL_TICKET_AGENT 16
#define MODIFY_TICKET_AGENT 17
#define PREV_BOOKINGS_AGENT 18
#define UPDATE_BOOKING_AGENT 19


#define PRINT_DETAILS 20
